### ISSUE TITLE
Fix fonts for non-mac users

### ISSUE THREAD

**Issue by mantagen** [Jbarget/oxymore#109]
Currently, there is no fallback for non-mac users (who don't have Helvetica on system).

https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/

Probably fine to just fallback to "sans-serif".

![image](https://user-images.githubusercontent.com/12934669/89784759-203cbd80-db11-11ea-87bc-421373a02cd7.png)

Also, just because I think you'll find it cool, and v useful in some circumstances:
https://css-tricks.com/simplified-fluid-typography/

**Comment by Jbarget** [comment]
so if people find the site through instagram (which is what Aitor thinks will happen) its likely the browser will be mobile safari, so we should definitely check that

**Comment by sssoja** [comment]
Good thinking @mantagen aaand also what with the Spanish translations there's gonna be a fair few uncommon ASCII characters like ñ and é.

Don't want to end up with:

<img width="402" alt="Screenshot 2020-09-18 at 13 22 16" src="https://user-images.githubusercontent.com/53219789/93592247-192b8980-f9b2-11ea-8441-f9c2bc82870f.png">
