### ISSUE TITLE
Header buttons are incorrectly positioned

### ISSUE THREAD

**Issue by mantagen** [Jbarget/oxymore#111]
Eg: "Oxymore" and "Menu"

![image](https://user-images.githubusercontent.com/12934669/89788212-b4f5ea00-db16-11ea-972e-6981108c116e.png)

Check across the different pages, it seems to differ

**Comment by sssoja** [comment]
I can't seem to recreate the issue @mantagen can you double check that this still happening?

**Comment by mantagen** [comment]
Ah, so for instance, on `/projects` the horizontal padding 32px, on `/oxymore` horizontal padding is 24px

**Comment by mantagen** [comment]
(whoops didn't mean to close)
