### ISSUE TITLE
Home page is larger than one screen

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#114]
Home page is larger than the screen so it has vertical scroll

![image](https://user-images.githubusercontent.com/11725595/92212977-18173a00-ee93-11ea-8e0e-cff112641dfe.png)

**Comment by Jbarget** [comment]
hmmm this seems to have gone now but i didnt work on this, lets keep an eye on it

**Comment by sssoja** [comment]
I think this is fixed now @Jbarget - see @mantagen 's handy work #136
