### ISSUE TITLE
Create a function so that only certain pages are deployed to the site  

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#139]
https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by Jbarget** [comment]
i dont follow what this ticket means, did this come out of yours and Aitors meeting?

**Comment by sssoja** [comment]
I've renamed the ticket @Jbarget hope that's clearer?

It came out of mine and Matt's chat we talked about using a custom env variable to deploy only the loading page to the `production` branch so that Aitor has somewhere to send visitors while we keep working on develop (countdown timer updated obv). 

As we're going to be launching the project pages one after another anyway, it makes sense to have a helper function that we can reuse for the same purpose.

**Comment by Jbarget** [comment]
I thought all project pages were going to have countdown timers, so im not sure which pages should be hidden. If thats the case I feel its a bit overkill to do this

**Comment by sssoja** [comment]
My misunderstanding. Will close the ticket
