### ISSUE TITLE
Swap in a higher res favicon

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#174]

**Comment by Jbarget** [comment]
can you put  screenshot of what yours looks like currently

**Comment by sssoja** [comment]
<img width="261" alt="Screenshot 2020-10-09 at 14 53 56" src="https://user-images.githubusercontent.com/53219789/95585251-46160e00-0a3f-11eb-91b2-06894a4a26e7.png">

**Comment by sssoja** [comment]
if you click on the image you'll be able to see what I mean @Jbarget

**Comment by Jbarget** [comment]
https://www.google.com/search?client=opera&q=favicon+size&sourceid=opera&ie=UTF-8&oe=UTF-8

we have a 16 x 16 favicon so i dont think this is necessary, if you agree close this issue :)
