### ISSUE TITLE
Compress all project and logo icons

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#179]
Currently a lot of the icons are larger than 1mb. That is massive, we need to get these numbers down in order for the website to load properly

![image](https://user-images.githubusercontent.com/11725595/95747846-63deaf80-0c99-11eb-85c4-a0ccd389fbef.png)

**Comment by sssoja** [comment]
Just redirecting to [here](https://github.com/Jbarget/oxymore/pull/140) as we left it a bit open-ended and I think we're all getting at the same thing...

**Comment by Jbarget** [comment]
Im not 100% sure what you mean by redirecting?

Id say let’s get all the icons compressed down, or you can ask the designer to provide you with smaller icons directly.

And then we can assess the situation after that (if we need to carry on optimising)
