### ISSUE TITLE
Move assets folder into public

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#188]

**Comment by sssoja** [comment]
@Jbarget would it be okay to move the asset folder outside of components but keep it inside src?

<img width="1438" alt="Screenshot 2020-10-15 at 19 02 28" src="https://user-images.githubusercontent.com/53219789/96162723-2a1bdc00-0f19-11eb-8cec-67a1b968a2f0.png">

**Comment by Jbarget** [comment]
i realised this is actually wrong after reading the documentation
