### ISSUE TITLE
Replace the placeholder text in Erotic Stories

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#216]

**Comment by sssoja** [comment]
@Jbarget I've moved this to a 2:

-  In the `translation.json` we have the text for each of the erotic stories but we need to format the string in such a way that it renders with line breaks and italics as seen in the story format here

<img width="679" alt="Screenshot 2020-11-16 at 12 37 07" src="https://user-images.githubusercontent.com/53219789/99248280-7b650700-2808-11eb-971e-5a2f0c53a654.png">

- I've tried splitting each of the parts up into individual keys and values, so for example, `bellyButtonsParagraph1: some text` but it's taking forever so I can tell it's not the solution

**Comment by sssoja** [comment]
Update. I used `dangerouslySetInnerHTML` but it's not giving me the expected result. Are you able to spot what I'm missing?@jbarget 

<img width="727" alt="Screenshot 2020-12-01 at 16 40 26" src="https://user-images.githubusercontent.com/53219789/100762328-21f9fc00-33f4-11eb-9f2a-672a83bafef7.png">

**Comment by Jbarget** [comment]
nice! if you wanna use `dangerouslySetInnerHTML` then in the string of the text, you can add `<i>some text</i>` for italics and the line breaks you can put into separate <p> tags

**Comment by sssoja** [comment]
full text with translation here: https://drive.google.com/drive/folders/1E-E-wUtrMGKSRXgviSYoelECdJwGXuad
