### ISSUE TITLE
bug on contact page

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#281]
@sssoja is the <br> supposed to be here?
![image](https://user-images.githubusercontent.com/11725595/101547024-f05fd280-39a9-11eb-98bb-f6518560acf2.png)

**Comment by Jbarget** [comment]
whoops just seen youve fixed this in #274

**Comment by sssoja** [comment]
Cool! could you approve s'il te plaît? @Jbarget

**Comment by sssoja** [comment]
Oh wait hang on I see what you mean ...

<img width="1429" alt="Screenshot 2020-12-09 at 11 40 31" src="https://user-images.githubusercontent.com/53219789/101619289-5cc2ec00-3a13-11eb-9730-85efb5c2aefb.png">

Let me look at that again
