### ISSUE TITLE
Move assets into public folder

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#284]

**Comment by Jbarget** [comment]
i thought we agreed this wasnt going to get done in https://github.com/Jbarget/oxymore/issues/188

**Comment by sssoja** [comment]
ah yeah, my bad. I thought this was convention. do you know which documentation that was? @Jbarget

**Comment by sssoja** [comment]
I can move back into src if thats all okay

**Comment by Jbarget** [comment]
https://create-react-app.dev/docs/using-the-public-folder/#adding-assets-outside-of-the-module-system

"Note that we normally encourage you to import assets in JavaScript files instead. For example, see the sections on adding a stylesheet and adding images and fonts. "

you wouldnt need to move them back, you just close the pr and delete the branch
