### ISSUE TITLE
Create burger menu

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#3]
![image](https://user-images.githubusercontent.com/53219789/84636848-5ab12200-aef5-11ea-9da0-48e7fd49dc2e.png)

![image](https://user-images.githubusercontent.com/53219789/84637135-a368db00-aef5-11ea-8ea2-2bbfa82dd950.png)

**Comment by sssoja** [comment]
<img width="1439" alt="Screenshot 2020-06-22 at 17 47 22" src="https://user-images.githubusercontent.com/53219789/85307802-a4c77400-b4b0-11ea-8349-42507dc37ae5.png">

**Comment by Jbarget** [comment]
@sssoja i know its a bit confusing, this is the issue, the screenshot is more suitable in the PR thats linked to this issue

#31 (add it not as a comment at the bottom, but add it to the description at the top)
![image](https://user-images.githubusercontent.com/11725595/85382535-5ad99f00-b53f-11ea-99d9-658f0c8f5c08.png)
