### ISSUE TITLE
Burger menu: Version 2.0

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#54]
**Nb** Menu items as follows: 

- About
- Manifesto
- Contact 
- Advertising
- Buy

<img width="715" alt="Screenshot 2020-07-13 at 15 28 58" src="https://user-images.githubusercontent.com/53219789/87310042-b0411480-c51d-11ea-902e-e9c8d3d905f0.png">

![iPhone 8 Plus - 3](https://user-images.githubusercontent.com/53219789/87310171-e41c3a00-c51d-11ea-8498-6ed6e9933fed.png)

**Comment by Jbarget** [comment]
the text on those two screeenshots is different, maybe check the menu items with Aitor

**Comment by sssoja** [comment]
> the text on those two screeenshots is different, maybe check the menu items with Aitor

Good spot, will update once he gets back to me
