### ISSUE TITLE
Create page: Loading

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#57]
- Create loading page using Alpha logo motion graphic
- Create timer with countdown functionality
- Aitor to send moving logo - we have this in PNG stills and video format
- optimal file size/extension?

**Comment by Jbarget** [comment]
@sssoja i would have thought the Loading page is the Timer component you've created? do you have designs for this?

**Comment by sssoja** [comment]
Correct. No designs, just the timer. Potentially with the moving graphic but Aitor still needs to get it from the designer

**Comment by Jbarget** [comment]
im gonna close this since this is done then, if Aitor wants more features we can create a new ticket after
