### ISSUE TITLE
Create page: About us

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#6]

**Comment by sssoja** [comment]
Hey @Jbarget can you PR this so I can see the code? Thanks!

**Comment by sssoja** [comment]
https://blog.logrocket.com/types-vs-interfaces-in-typescript/

**Comment by Jbarget** [comment]
@sssoja do we have the assets and text for this page?

**Comment by sssoja** [comment]
Yeah the assets are in the drive [here](https://drive.google.com/drive/folders/1Rvc2HZktI2gpj9SC774nv6opm_A2dD5s), I could have sworn I uploaded the Figma design for the About page on to a ticket along with all the other design updates when I had that meeting with Aitor a few months back. 

Can't seem to find it now so here it is below.

![Desktop - 4](https://user-images.githubusercontent.com/53219789/92260550-5a169f00-eed8-11ea-83f0-0e1605189748.png)

**Comment by Jbarget** [comment]
You don’t need to comment on the issue, it closes automatically when the PR is merged because wevee put “fixes #{issue number}” in the description
