### ISSUE TITLE
Create page: Advertising

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#7]

**Comment by Jbarget** [comment]
@sssoja do you know if we have designs for this yet?

**Comment by sssoja** [comment]
Just spoken with Aitor, there's no designs so we've just settled on 2 images and some text. The images will be half screen in width and display on desktop like a magazine spread with a bit of text underneath.

This is one of the images: 

![voltrova ad](https://user-images.githubusercontent.com/53219789/92372399-28cae880-f0fd-11ea-868b-4334a8fed76e.jpg)

**Comment by Jbarget** [comment]
@sssoja can you add the designs for this page here so i know what it should look like

**Comment by sssoja** [comment]
We don't have any designs.. @Jbarget

**Comment by sssoja** [comment]
Closing as #149 is in progress
