### ISSUE TITLE
Project 9: Kai Landre Video

### ISSUE THREAD

**Issue by Jbarget** [Jbarget/oxymore#8]
![image](https://user-images.githubusercontent.com/53219789/84635791-00639180-aef4-11ea-909c-0779450cce5f.png)

**Comment by sssoja** [comment]
https://www.npmjs.com/package/react-youtube

**Comment by sssoja** [comment]
https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations

**Comment by sssoja** [comment]
https://www.youtube.com/watch?v=_nBlN9yp9R8

**Comment by sssoja** [comment]
https://github.com/CookPete/react-player#props
