### ISSUE TITLE
Create timer component with countdown functionality

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#83]
Create a reusable countdown component using React hooks

**Comment by Jbarget** [comment]
this should be in the Review in progress column?

**Comment by sssoja** [comment]
> this should be in the Review in progress column?

 I moved it to To Do as I started work on the PR comments and then parked it because couldn't get the implementation right and wanted to get other stuff done. Should I move it back to Review in Progress?

**Comment by Jbarget** [comment]
yah with PR comments it should still live in Review in progress 👍
