### ISSUE TITLE
Fix display issue on nav menu

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#92]
The padding on the `<Main>` tag is pushing down the nav overlay meaning that it doesn't cover the whole screen.

<img width="1440" alt="Screenshot 2020-08-04 at 13 44 01" src="https://user-images.githubusercontent.com/53219789/89290117-a613c100-d658-11ea-9105-bb12d0f49328.png">

**Comment by Jbarget** [comment]
can you add a screenshot of the issue

**Comment by sssoja** [comment]
> can you add a screenshot of the issue
> 
> description updated with screenshot
description updated with screenshot

**Comment by sssoja** [comment]
> can you add a screenshot of the issue

description updated with screenshot
