### ISSUE TITLE
Add header component to about page

### ISSUE THREAD

**Issue by sssoja** [Jbarget/oxymore#99]

**Comment by Jbarget** [comment]
So with all of these new issues about adding the Header to all the pages, its best to just add the header in the parent component (keeping the code DRY) so it appears on all the pages

**Comment by sssoja** [comment]
Hey, I don't want it to appear on all pages. That's why =) 

Also I deleted most of the tickets. That was just a process of me figuring it out in my head.

**Comment by Jbarget** [comment]
Which list is shorter, pages you want it to appear on or pages you don't want it to appear on?

**Comment by Jbarget** [comment]
Its best to create one issue and in the description put a bulletpoint list of all the pages you want to add it to, removes the noise

**Comment by sssoja** [comment]
Wait my bad, I thought I'd deleted all these issues but turns out they still existed they were just not on the project board @Jbarget 

I've closed them all now. I hear ya by the way - just rushed a bit opening them all but realised it wasn't necessary

**Comment by sssoja** [comment]
Which list is shorter, pages you want it to appear on or pages you don't want it to appear on?

It's more of a question of how to have the `NavMenu` sit on the Homepage.

If you want to have the `Header` on the `App` component, then how do you select which of its child elements appear on certain pages and those that do not? 

On the Homepage we want only the Nav Menu to appear and not the entire header. 

The `Header` component is an imported Component made up of children. So you can't just pick and choose which elements are displayed. That's why the  `NavMenu.ts` needs to be used here. 

Unfortunately, it's a bit of a Rubik's cube design wise as you're having to untangle inherited styles from the `NavMenu`, the `Header` and those of each of the different pages. 

I've been working for a few weeks now on this issue. I just opened a new branch specifically for it - you can track my progress here #92

**Comment by Jbarget** [comment]
> So you can't just pick and choose which elements are displayed.

You can, theres a few ways to do it but maybe a standard `if` statement would be simplest
https://scotch.io/tutorials/7-ways-to-implement-conditional-rendering-in-react-applications#toc-1-using-an-if-else-statement

**Comment by sssoja** [comment]
> > So you can't just pick and choose which elements are displayed.
> 
> You can, theres a few ways to do it but maybe a standard `if` statement would be simplest
> https://scotch.io/tutorials/7-ways-to-implement-conditional-rendering-in-react-applications#toc-1-using-an-if-else-statement

Sick, gonna try
